{
    'name': 'Demo Process',
    'version': '17.0.0.1',
    'summary': 'A custom module for Odoo 17',
    'description': 'IDMT - Demo Process',
    'author': 'Digimeta',
    'website': 'https://www.digimeta.dev/',
    'category': 'Custom',
    'depends': ['base','hr', 'custom_hr_employee','employee_escalation','employee_production'],
    'data': [
        'security/access_groups.xml',
        'security/ir.model.access.csv',
        'wizard/notes_upload_wizard_views.xml',
        'reports/demo_search_report.xml',
        'views/allocation/demo_process_ams_allocation_view.xml',
        'views/allocation/demo_process_cama_allocation_view.xml',
        'views/allocation/demo_process_cama_charges_allocation_view.xml',
        'views/allocation/demo_process_pa_allocation_view.xml',
        'views/allocation/demo_process_pa_charges_allocation_view.xml',
        'views/allocation/demo_process_avala_allocation_view.xml',
        'views/allocation/demo_process_wta_allocation_view.xml',
        'views/production/demo_process_ams_production_view.xml',
        'views/production/demo_process_cama_charges_production_view.xml',
        'views/production/demo_process_cama_production_view.xml',
        'views/production/demo_process_pa_charges_production_view.xml',
        'views/production/demo_process_avala_production_view.xml',
        'views/production/demo_process_pa_production_view.xml',
        'views/production/demo_process_wta_production_view.xml',
        'views/audit_allocation/demo_process_ams_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_cama_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_cama_charges_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_pa_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_pa_charges_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_avala_audit_allocation_view.xml',
        'views/audit_allocation/demo_process_wta_audit_allocation_view.xml',
        'views/quality_assurance/demo_process_ams_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_cama_charges_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_cama_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_pa_charges_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_avala_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_pa_quality_assurance_view.xml',
        'views/quality_assurance/demo_process_wta_quality_assurance_view.xml',
        'views/reprocessing/demo_process_ams_reprocessing_view.xml',
        'views/reprocessing/demo_process_cama_charges_reprocessing_view.xml',
        'views/reprocessing/demo_process_cama_reprocessing_view.xml',
        'views/reprocessing/demo_process_pa_charges_reprocessing_view.xml',
        'views/reprocessing/demo_process_avala_reprocessing_view.xml',
        'views/reprocessing/demo_process_pa_reprocessing_view.xml',
        'views/reprocessing/demo_process_wta_reprocessing_view.xml',
        'views/reporting/demo_process_ams_reporting_view.xml',
        'views/reporting/demo_process_cama_charges_reporting_view.xml',
        'views/reporting/demo_process_cama_reporting_view.xml',
        'views/reporting/demo_process_pa_charges_reporting_view.xml',
        'views/reporting/demo_process_avala_reporting_view.xml',
        'views/reporting/demo_process_pa_reporting_view.xml',
        'views/reporting/demo_process_wta_reporting_view.xml',
        'views/reporting/demo_process_consolidated_reporting_view.xml',
        'views/record_reporting/record_demo_process_ams_reporting_view.xml',
        'views/record_reporting/record_demo_process_cama_reporting_view.xml',
        'views/record_reporting/record_demo_process_pa_reporting_view.xml',
        'views/record_reporting/record_demo_process_wta_reporting_view.xml',
        'views/record_reporting/record_demo_process_cama_charges_reporting_view.xml',
        'views/record_reporting/record_demo_process_pa_charges_reporting_view.xml',
        'views/record_reporting/record_demo_process_avala_reporting_view.xml',
        'views/record_reporting/record_demo_process_consolidated_reporting_view.xml',
        'views/masters/demo_station_view.xml',
        'views/masters/error_category_views.xml',
        'views/masters/facility_view.xml',
        'views/masters/login_id_view.xml',
        'views/masters/reprocessing_status_view.xml',
        'views/masters/status_view.xml',
        'views/masters/demo_process_audit_status_view.xml',
        'views/masters/demo_process_user_remarks_view.xml',
        'views/target/demo_process_employee_target_view.xml',
        'views/target/demo_process_employee_production_view.xml',
        'views/employee_escalation_view.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}