{
    'name': 'Payment Posting ETM',
    'version': '17.0.0.1',
    'summary': 'A custom module for Odoo 17',
    'description': 'IDMT - EDM Process',
    'author': 'Digimeta',
    'website': 'https://www.digimeta.dev/',
    'category': 'Custom',
    'depends': ['base', 'payment_posting'],
    'data': [
        'security/etm_security.xml',
        'security/ir.model.access.csv',
        'views/pp_etm/allocation/pp_adjustments_view.xml',
        'views/pp_etm/allocation/pp_chk_research_view.xml',
        'views/pp_etm/allocation/pp_corrections_view.xml',
        'views/pp_etm/allocation/pp_denials_view.xml',
        'views/pp_etm/allocation/pp_transfer_view.xml',
        'views/pp_etm/production/pp_production_adjustments_view.xml',
        'views/pp_etm/production/pp_production_chk_research_view.xml',
        'views/pp_etm/production/pp_production_corrections_view.xml',
        'views/pp_etm/production/pp_production_denials_view.xml',
        'views/pp_etm/production/pp_production_transfer_view.xml',
        'views/pp_etm/quality_allocation/pp_quality_allocation_adjustments_view.xml',
        'views/pp_etm/quality_allocation/pp_quality_allocation_chk_research_view.xml',
        'views/pp_etm/quality_allocation/pp_quality_allocation_corrections_view.xml',
        'views/pp_etm/quality_allocation/pp_quality_allocation_denials_view.xml',
        'views/pp_etm/quality_allocation/pp_quality_allocation_transfer_view.xml',
        'views/pp_etm/quality_assurance/pp_quality_assurance_adjustments_view.xml',
        'views/pp_etm/quality_assurance/pp_quality_assurance_chk_research_view.xml',
        'views/pp_etm/quality_assurance/pp_quality_assurance_corrections_view.xml',
        'views/pp_etm/quality_assurance/pp_quality_assurance_denials_view.xml',
        'views/pp_etm/quality_assurance/pp_quality_assurance_transfer_view.xml',
        'views/pp_etm/reprocessing/pp_reprocessing_adjustments_view.xml',
        'views/pp_etm/reprocessing/pp_reprocessing_chk_research_view.xml',
        'views/pp_etm/reprocessing/pp_reprocessing_corrections_view.xml',
        'views/pp_etm/reprocessing/pp_reprocessing_denials_view.xml',
        'views/pp_etm/reprocessing/pp_reprocessing_transfer_view.xml',
        'views/pp_etm/reporting/pp_reporting_adjustments_view.xml',
        'views/pp_etm/reporting/pp_reporting_chk_research_view.xml',
        'views/pp_etm/reporting/pp_reporting_corrections_view.xml',
        'views/pp_etm/reporting/pp_reporting_denials_view.xml',
        'views/pp_etm/reporting/pp_reporting_transfer_view.xml',
        'views/masters/action_taken_view.xml',
        'views/masters/adjustment_reasons_view.xml',
        'views/pp_etm/combined_etm_view.xml',
        'views/menu.xml',
        'views/pp_etm/query_processing/etm_query_processing_posting_clarification_view.xml',
        'views/pp_etm/query_processing/etm_query_processing_utility_request_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}