{
    'name': 'Payment Posting',
    'version': '17.0.0.1',
    'summary': 'A custom module for Odoo 17',
    'description': 'IDMT - EDM Process',
    'author': 'Digimeta',
    'website': 'https://www.digimeta.dev/',
    'category': 'Custom',
    'depends': ['base', 'mail', 'hr','custom_hr_employee'],
    'data': [
        'security/access_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/edm/payment_posting_production.xml',
        'views/ecom/payment_posting_ecom_view.xml',
        'views/835_push/payment_posting_835_push_view.xml',
        'views/edm/payment_posting_allocation.xml',
        'views/ecom/payment_posting_allocation_ecom.xml',
        'views/835_push/payment_posting_allocation_835_push.xml',
        'views/edm/payment_posting_quality.xml',
        'views/ecom/payment_posting_quality_ecom.xml',
        'views/835_push/payment_posting_quality_835_push.xml',
        'views/edm/payment_posting_quality_assurance.xml',
        'views/ecom/payment_posting_quality_assurance_ecom.xml',
        'views/835_push/payment_posting_quality_assurance_835_push.xml',
        'views/remarks_view.xml',
        'views/status_view.xml',
        'views/division_master_view.xml',
        'views/audit_status_view.xml',
        'views/reprocessing_status_view.xml',
        'views/error_category_views.xml',
        'views/edm/payment_posting_reprocessing_status.xml',
        'views/ecom/payment_posting_reprocessing_status_ecom.xml',
        'views/835_push/payment_posting_reprocessing_status_835_push.xml',
        'views/edm/reporting_view.xml',
        'views/reporting_my_production.xml',
        'views/ecom/reporting_ecom_view.xml',
        'views/835_push/reporting_835_push_view.xml',
        'views/tags_view.xml',
        'views/escalation_type_view.xml',
        'views/q_status_view.xml',
        'views/ss_status_view.xml',
        'views/res_config_settings_views.xml',
        'views/import/import_edm_payment_posting_view.xml',
        'views/import/import_ecom_payment_posting_view.xml',
        'views/query_processing/query_processing_utility_request_view.xml',
        'views/query_processing/query_processing_posting_clarification_view.xml',
        'views/target/employee_target_view.xml',
        'wizard/employee_target_wizard_view.xml',
        'views/target/employee_production_view.xml',
        'reports/ahm_report.xml',
        'views/hr_employee.xml',
        'views/employee_escalation_view.xml'
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}